name: Python build
on:
  workflow_dispatch:

jobs:
  build:
    name: Python build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt 

      - name: Generate SBOM
        run: cyclonedx-py --e --format json -o cyclonedx-sbom.json

      - name: Convert SBOM
        uses: duosecurity/duo_client_python/.github/actions/sbom-convert@master

      - name: Build
        run: python -m build
